services:
  db:
    image: postgres:15-alpine
    container_name: escola-db
    environment:
      POSTGRES_USER: userifs
      POSTGRES_PASSWORD: senha-ifs
      POSTGRES_DB: escola
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build: .
    container_name: escola-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: userifs
      DB_PASSWORD: senha-ifs
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: escola
    depends_on:
      - db

volumes:
  pgdata:
